// Mocks generated by Mockito 5.0.17 from annotations
// in bima/test/features/doctor/presentation/bloc/doctor_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:bima/core/error/failure.dart' as _i6;
import 'package:bima/core/usecases/usecases.dart' as _i8;
import 'package:bima/features/doctor/domain/entities/doctor.dart' as _i7;
import 'package:bima/features/doctor/domain/repositories/doctor_repository.dart'
    as _i2;
import 'package:bima/features/doctor/domain/use_cases/get_all_doctors.dart'
    as _i3;
import 'package:bima/features/doctor/domain/use_cases/update_doctor_detail.dart'
    as _i9;
import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDoctorRepository_0 extends _i1.Fake implements _i2.DoctorRepository {
}

/// A class which mocks [GetAllDoctors].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllDoctors extends _i1.Mock implements _i3.GetAllDoctors {
  @override
  _i2.DoctorRepository get doctorRepository =>
      (super.noSuchMethod(Invocation.getter(#doctorRepository),
          returnValue: _FakeDoctorRepository_0()) as _i2.DoctorRepository);
  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i7.DoctorEntity>>?> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<
                  _i5.Either<_i6.Failure, List<_i7.DoctorEntity>>?>.value())
          as _i4.Future<_i5.Either<_i6.Failure, List<_i7.DoctorEntity>>?>);
}

/// A class which mocks [UpdateDoctorDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateDoctorDetail extends _i1.Mock
    implements _i9.UpdateDoctorDetail {
  @override
  _i2.DoctorRepository get doctorRepository =>
      (super.noSuchMethod(Invocation.getter(#doctorRepository),
          returnValue: _FakeDoctorRepository_0()) as _i2.DoctorRepository);
  @override
  _i4.Future<_i5.Either<_i6.Failure, void>?> call(_i7.DoctorEntity? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i5.Either<_i6.Failure, void>?>.value())
          as _i4.Future<_i5.Either<_i6.Failure, void>?>);
}
